1.Import liabraies

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

2.Load data

In [7]:
df=pd.read_csv("patienthistory.csv")
df.head()

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
0,857781,0,0,1,0,0.0,1,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0
1,743087,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0
2,866418,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0
3,775928,0,0,1,0,0.0,0,1.0,0,0,0,0,0.0,0,2.0,nontypeii,0
4,810128,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,0.0,nontypeii,0

In [ ]:
3.Check the number of rows and columns

In [6]:
df.shape

(2008, 17)

4. All columns names

In [7]:
df.columns

Index(['inpatient_number', 'cerebrovascular_disease', 'dementia',
       'chronic_obstructive_pulmonary_disease', 'connective_tissue_disease',
       'peptic_ulcer_disease', 'diabetes',
       'moderate_to_severe_chronic_kidney_disease', 'hemiplegia', 'leukemia',
       'malignant_lymphoma', 'solid_tumor', 'liver_disease', 'aids',
       'cci_score', 'type_ii_respiratory_failure', 'acute_renal_failure'],
      dtype='str')

5.Understand Datatypes

In [8]:
df.dtypes

inpatient_number                               int64
cerebrovascular_disease                        int64
dementia                                       int64
chronic_obstructive_pulmonary_disease          int64
connective_tissue_disease                      int64
peptic_ulcer_disease                         float64
diabetes                                       int64
moderate_to_severe_chronic_kidney_disease    float64
hemiplegia                                     int64
leukemia                                       int64
malignant_lymphoma                             int64
solid_tumor                                    int64
liver_disease                                float64
aids                                           int64
cci_score                                    float64
type_ii_respiratory_failure                      str
acute_renal_failure                            int64
dtype: object

In [9]:
df.sample(10, random_state=42)

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
1592,748910,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,1.0,nontypeii,0
526,769902,0,0,0,0,0.0,1,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0
393,760663,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,1.0,nontypeii,0
1403,846158,0,0,0,0,0.0,1,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0
433,778444,0,1,0,0,0.0,0,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0
576,823812,0,0,0,0,0.0,1,1.0,0,0,0,0,0.0,0,3.0,nontypeii,0
1087,781696,0,0,0,0,0.0,1,0.0,0,0,0,0,0.0,0,3.0,nontypeii,0
429,805435,0,0,0,0,0.0,0,0.0,0,0,0,0,0.0,0,1.0,nontypeii,0
611,834310,1,1,0,0,0.0,0,0.0,0,0,0,0,0.0,0,3.0,nontypeii,0
530,827105,0,0,0,0,0.0,1,0.0,0,0,0,0,0.0,0,2.0,nontypeii,0

6.Check the Duplicate rows

In [8]:
df.duplicated().sum()

np.int64(0)

7.Check duplicate patient IDs

In [10]:
df['inpatient_number'].duplicated().sum()

np.int64(0)

### Check unique patients id,length of data

In [55]:
df['inpatient_number'].nunique()

2008

In [12]:
len(df)

2008

8.Column by column cleaning

In [13]:
df['inpatient_number'].describe()

count      2008.000000
mean     797747.542829
std       41127.801740
min      722128.000000
25%      763164.500000
50%      798758.000000
75%      829399.750000
max      905720.000000
Name: inpatient_number, dtype: float64

Check missing value

In [14]:
df['inpatient_number'].isnull().sum()

np.int64(0)

Check duplicates

In [15]:
df['inpatient_number'].duplicated().sum()

np.int64(0)

9.check each columns values

In [26]:
df['cerebrovascular_disease'].value_counts(dropna=False)
df['dementia'].value_counts(dropna=False)
df['chronic_obstructive_pulmonary_disease'].value_counts(dropna=False)
df['connective_tissue_disease'].value_counts(dropna=False)
df['peptic_ulcer_disease'].value_counts(dropna=False)
df['diabetes'].value_counts(dropna=False)
df['moderate_to_severe_chronic_kidney_disease'].value_counts(dropna=False)
df['hemiplegia'].value_counts(dropna=False)
df['leukemia'].value_counts(dropna=False)
df['malignant_lymphoma'].value_counts(dropna=False)
df['solid_tumor'].value_counts(dropna=False)
df['liver_disease'].value_counts(dropna=False)
df['aids'].value_counts(dropna=False)
df['cci_score'].value_counts(dropna=False)
df['type_ii_respiratory_failure'].value_counts(dropna=False)
df['acute_renal_failure'].value_counts(dropna=False)

acute_renal_failure
0    2001
1       7
Name: count, dtype: int64

In [30]:
df['peptic_ulcer_disease'].value_counts(dropna=False)

peptic_ulcer_disease
0.0    1961
1.0      45
NaN       2
Name: count, dtype: int64

In [27]:
df['dementia'].value_counts(dropna=False)

dementia
0    1893
1     115
Name: count, dtype: int64

In [28]:
df['connective_tissue_disease'].value_counts(dropna=False)

connective_tissue_disease
0    2004
1       4
Name: count, dtype: int64

In [29]:
df['type_ii_respiratory_failure'].value_counts(dropna=False)

type_ii_respiratory_failure
nontypeii    1894
typeii        114
Name: count, dtype: int64

In [31]:
df['diabetes'].value_counts(dropna=False)

diabetes
0    1542
1     466
Name: count, dtype: int64

In [32]:
df['moderate_to_severe_chronic_kidney_disease'].value_counts(dropna=False)

moderate_to_severe_chronic_kidney_disease
0.0    1532
1.0     474
NaN       2
Name: count, dtype: int64

In [33]:
df['hemiplegia'].value_counts(dropna=False)

hemiplegia
0    1996
1      12
Name: count, dtype: int64

In [34]:
df['leukemia'].value_counts(dropna=False)

leukemia
0    2008
Name: count, dtype: int64

In [35]:
df['malignant_lymphoma'].value_counts(dropna=False)

malignant_lymphoma
0    2007
1       1
Name: count, dtype: int64

In [36]:
df['solid_tumor'].value_counts(dropna=False)

solid_tumor
0    1969
1      39
Name: count, dtype: int64

In [37]:
df['liver_disease'].value_counts(dropna=False)

liver_disease
0.0    1923
1.0      84
NaN       1
Name: count, dtype: int64

In [38]:
df['aids'].value_counts(dropna=False)

aids
0    2004
1       4
Name: count, dtype: int64

In [39]:
df['cci_score'].value_counts(dropna=False)

cci_score
1.0    770
2.0    699
3.0    368
4.0     94
0.0     56
5.0     15
NaN      5
6.0      1
Name: count, dtype: int64

In [ ]:
Check missing values

In [ ]:
df['chronic_obstructive_pulmonary_disease'].isnull().sum()

In [40]:
df['cerebrovascular_disease'].isnull().sum()
df['dementia'].isnull().sum()
df['chronic_obstructive_pulmonary_disease'].isnull().sum()
df['connective_tissue_disease'].isnull().sum()
df['peptic_ulcer_disease'].isnull().sum()
df['diabetes'].isnull().sum()
df['moderate_to_severe_chronic_kidney_disease'].isnull().sum()
df['hemiplegia'].isnull().sum()
df['leukemia'].isnull().sum()
df['malignant_lymphoma'].isnull().sum()
df['solid_tumor'].isnull().sum()
df['liver_disease'].isnull().sum()
df['aids'].isnull().sum()
df['cci_score'].isnull().sum()
df['type_ii_respiratory_failure'].isnull().sum()
df['acute_renal_failure'].isnull().sum()

np.int64(0)

In [41]:
df['cci_score'].isnull().sum()

np.int64(5)

In [42]:
df['peptic_ulcer_disease'].value_counts(dropna=False)

peptic_ulcer_disease
0.0    1961
1.0      45
NaN       2
Name: count, dtype: int64

There are 2 missing values ,this important because we should see which patients has missing values

In [43]:
df.loc[
    df['peptic_ulcer_disease'].isnull(),
    ['inpatient_number', 'peptic_ulcer_disease']
]

      inpatient_number  peptic_ulcer_disease
817             794590                   NaN
1003            818307                   NaN

In [44]:
df['moderate_to_severe_chronic_kidney_disease'].value_counts(dropna=False)

moderate_to_severe_chronic_kidney_disease
0.0    1532
1.0     474
NaN       2
Name: count, dtype: int64

In [46]:
df.loc[
    df['moderate_to_severe_chronic_kidney_disease'].isnull(),
    ['inpatient_number', 'moderate_to_severe_chronic_kidney_disease']
]

     inpatient_number  moderate_to_severe_chronic_kidney_disease
467            782088                                        NaN
743            791916                                        NaN

In [47]:
df['liver_disease'].value_counts(dropna=False)

liver_disease
0.0    1923
1.0      84
NaN       1
Name: count, dtype: int64

In [48]:
df.loc[
    df['liver_disease'].isnull(),
    ['inpatient_number', 'liver_disease']
]

      inpatient_number  liver_disease
1497            793609            NaN

In [49]:
df['cci_score'].value_counts(dropna=False)

cci_score
1.0    770
2.0    699
3.0    368
4.0     94
0.0     56
5.0     15
NaN      5
6.0      1
Name: count, dtype: int64

In [50]:
df.loc[
    df['cci_score'].isnull(),
    ['inpatient_number', 'cci_score']
]

      inpatient_number  cci_score
467             782088        NaN
743             791916        NaN
817             794590        NaN
1003            818307        NaN
1497            793609        NaN

How should you handle it?

Because this is a binary medical-history variable, do not automatically use the mean or median.

If your data dictionary says that blank means "no disease," then you can use:

checking for blank

In [53]:
missing_percentage = df.isnull().mean() * 100

missing_percentage

inpatient_number                             0.000000
cerebrovascular_disease                      0.000000
dementia                                     0.000000
chronic_obstructive_pulmonary_disease        0.000000
connective_tissue_disease                    0.000000
peptic_ulcer_disease                         0.099602
diabetes                                     0.000000
moderate_to_severe_chronic_kidney_disease    0.099602
hemiplegia                                   0.000000
leukemia                                     0.000000
malignant_lymphoma                           0.000000
solid_tumor                                  0.000000
liver_disease                                0.049801
aids                                         0.000000
cci_score                                    0.249004
type_ii_respiratory_failure                  0.000000
acute_renal_failure                          0.000000
dtype: float64

In [54]:
missing_report = pd.DataFrame({
    'Missing Count': df.isnull().sum(),
    'Missing Percentage': (df.isnull().mean() * 100).round(2)
})

missing_report

                                           Missing Count  Missing Percentage
inpatient_number                                       0                0.00
cerebrovascular_disease                                0                0.00
dementia                                               0                0.00
chronic_obstructive_pulmonary_disease                  0                0.00
connective_tissue_disease                              0                0.00
peptic_ulcer_disease                                   2                0.10
diabetes                                               0                0.00
moderate_to_severe_chronic_kidney_disease              2                0.10
hemiplegia                                             0                0.00
leukemia                                               0                0.00
malignant_lymphoma                                     0                0.00
solid_tumor                                            0                0.00
liver_disease                                          1                0.05
aids                                                   0                0.00
cci_score                                              5                0.25
type_ii_respiratory_failure                            0                0.00
acute_renal_failure                                    0                0.00

Display only columns that contain blanks

In [56]:
missing_report[missing_report['Missing Count'] > 0]

                                           Missing Count  Missing Percentage
peptic_ulcer_disease                                   2                0.10
moderate_to_severe_chronic_kidney_disease              2                0.10
liver_disease                                          1                0.05
cci_score                                              5                0.25

Find which patient and which column is blank

In [57]:
df[df.isnull().any(axis=1)]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure
467,782088,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,0
743,791916,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,1
817,794590,0,0,0,0,NaN,1,1.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1003,818307,0,0,0,0,NaN,1,0.0,0,0,0,0,0.0,0,NaN,nontypeii,0
1497,793609,0,0,0,0,0.0,1,1.0,0,0,0,0,NaN,0,NaN,nontypeii,0

Find which patient and which column is blank

In [58]:
for index, row in df.iterrows():
    missing_columns = row[row.isnull()].index.tolist()
    
    if missing_columns:
        print(
            "Row:", index,
            "| Inpatient Number:", row['inpatient_number'],
            "| Blank Columns:", missing_columns
        )

Row: 467 | Inpatient Number: 782088 | Blank Columns: ['moderate_to_severe_chronic_kidney_disease', 'cci_score']
Row: 743 | Inpatient Number: 791916 | Blank Columns: ['moderate_to_severe_chronic_kidney_disease', 'cci_score']
Row: 817 | Inpatient Number: 794590 | Blank Columns: ['peptic_ulcer_disease', 'cci_score']
Row: 1003 | Inpatient Number: 818307 | Blank Columns: ['peptic_ulcer_disease', 'cci_score']
Row: 1497 | Inpatient Number: 793609 | Blank Columns: ['liver_disease', 'cci_score']

Check all four columns with missing values

In [59]:
columns_to_check = [
    'peptic_ulcer_disease',
    'moderate_to_severe_chronic_kidney_disease',
    'liver_disease',
    'cci_score'
]

df[
    df[columns_to_check].isnull().any(axis=1)
][
    ['inpatient_number'] + columns_to_check
]

,inpatient_number,peptic_ulcer_disease,moderate_to_severe_chronic_kidney_disease,liver_disease,cci_score
467,782088,0.0,NaN,0.0,NaN
743,791916,0.0,NaN,0.0,NaN
817,794590,NaN,1.0,0.0,NaN
1003,818307,NaN,0.0,0.0,NaN
1497,793609,0.0,1.0,NaN,NaN

Check for actual blank strings

isnull() detects NaN, but sometimes CSV files contain empty strings

In [60]:
blank_strings = df.apply(
    lambda col: col.astype(str).str.strip().eq('').sum()
)

blank_strings

inpatient_number                             0
cerebrovascular_disease                      0
dementia                                     0
chronic_obstructive_pulmonary_disease        0
connective_tissue_disease                    0
peptic_ulcer_disease                         0
diabetes                                     0
moderate_to_severe_chronic_kidney_disease    0
hemiplegia                                   0
leukemia                                     0
malignant_lymphoma                           0
solid_tumor                                  0
liver_disease                                0
aids                                         0
cci_score                                    0
type_ii_respiratory_failure                  0
acute_renal_failure                          0
dtype: int64

Check blanks row-by-row

In [61]:
df['blank_count'] = df.isnull().sum(axis=1)

In [62]:
df[
    ['inpatient_number', 'blank_count']
].sort_values(
    'blank_count',
    ascending=False
)

      inpatient_number  blank_count
1003            818307            2
817             794590            2
743             791916            2
467             782088            2
1497            793609            2
...                ...          ...
1987            759370            0
1988            829624            0
1989            807293            0
1990            805610            0
7               787530            0

[2008 rows x 2 columns]

In [ ]:
Show only patients who have blanks

In [63]:
df[df['blank_count'] > 0]

,inpatient_number,cerebrovascular_disease,dementia,chronic_obstructive_pulmonary_disease,connective_tissue_disease,peptic_ulcer_disease,diabetes,moderate_to_severe_chronic_kidney_disease,hemiplegia,leukemia,malignant_lymphoma,solid_tumor,liver_disease,aids,cci_score,type_ii_respiratory_failure,acute_renal_failure,blank_count
467,782088,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,0,2
743,791916,0,0,0,0,0.0,1,NaN,0,0,0,0,0.0,0,NaN,nontypeii,1,2
817,794590,0,0,0,0,NaN,1,1.0,0,0,0,0,0.0,0,NaN,nontypeii,0,2
1003,818307,0,0,0,0,NaN,1,0.0,0,0,0,0,0.0,0,NaN,nontypeii,0,2
1497,793609,0,0,0,0,0.0,1,1.0,0,0,0,0,NaN,0,NaN,nontypeii,0,2

Important: Don't immediately replace blanks with 0

For your patienthistory.csv, we have binary disease variables such as:

peptic_ulcer_disease
liver_disease
moderate_to_severe_chronic_kidney_disease

Suppose you find:

liver_disease = NaN

Don't immediately do:

df['liver_disease'] = df['liver_disease'].fillna(0)

because:

0 = confirmed absence of disease
NaN = information is missing/unknown

These are not necessarily the same.

In [ ]:
Special case: cci_score
cci_score has 5 missing values.

In [64]:
df.loc[
    df['cci_score'].isnull(),
    [
        'inpatient_number',
        'cerebrovascular_disease',
        'dementia',
        'diabetes',
        'liver_disease',
        'aids',
        'cci_score'
    ]
]

,inpatient_number,cerebrovascular_disease,dementia,diabetes,liver_disease,aids,cci_score
467,782088,0,0,1,0.0,0,NaN
743,791916,0,0,1,0.0,0,NaN
817,794590,0,0,1,0.0,0,NaN
1003,818307,0,0,1,0.0,0,NaN
1497,793609,0,0,1,NaN,0,NaN

In [ ]:
Final blank check

In [65]:
print("Total rows:", len(df))
print("Total columns:", len(df.columns))
print("Total missing cells:", df.isnull().sum().sum())

Total rows: 2008
Total columns: 18
Total missing cells: 10

In [66]:
print("\nMissing values by column:")
print(df.isnull().sum())

Missing values by column:
inpatient_number                             0
cerebrovascular_disease                      0
dementia                                     0
chronic_obstructive_pulmonary_disease        0
connective_tissue_disease                    0
peptic_ulcer_disease                         2
diabetes                                     0
moderate_to_severe_chronic_kidney_disease    2
hemiplegia                                   0
leukemia                                     0
malignant_lymphoma                           0
solid_tumor                                  0
liver_disease                                1
aids                                         0
cci_score                                    5
type_ii_respiratory_failure                  0
acute_renal_failure                          0
blank_count                                  0
dtype: int64

In [67]:
print("\nRows containing missing values:")
print(df[df.isnull().any(axis=1)])

Rows containing missing values:
      inpatient_number  cerebrovascular_disease  dementia  \
467             782088                        0         0
743             791916                        0         0
817             794590                        0         0
1003            818307                        0         0
1497            793609                        0         0

      chronic_obstructive_pulmonary_disease  connective_tissue_disease  \
467                                       0                          0
743                                       0                          0
817                                       0                          0
1003                                      0                          0
1497                                      0                          0

      peptic_ulcer_disease  diabetes  \
467                    0.0         1
743                    0.0         1
817                    NaN         1
1003                   NaN         1
1497                   0.0         1

      moderate_to_severe_chronic_kidney_disease  hemiplegia  leukemia  \
467                                         NaN           0         0
743                                         NaN           0         0
817                                         1.0           0         0
1003                                        0.0           0         0
1497                                        1.0           0         0

      malignant_lymphoma  solid_tumor  liver_disease  aids  cci_score  \
467                    0            0            0.0     0        NaN
743                    0            0            0.0     0        NaN
817                    0            0            0.0     0        NaN
1003                   0            0            0.0     0        NaN
1497                   0            0            NaN     0        NaN

     type_ii_respiratory_failure  acute_renal_failure  blank_count
467                    nontypeii                    0            2
743                    nontypeii                    1            2
817                    nontypeii                    0            2
1003                   nontypeii                    0            2
1497                   nontypeii                    0            2

Show exact patient with blank column

In [68]:
for index, row in df.iterrows():
    missing = row[row.isnull()].index.tolist()
    if missing:
        print(row['inpatient_number'], missing)

782088 ['moderate_to_severe_chronic_kidney_disease', 'cci_score']
791916 ['moderate_to_severe_chronic_kidney_disease', 'cci_score']
794590 ['peptic_ulcer_disease', 'cci_score']
818307 ['peptic_ulcer_disease', 'cci_score']
793609 ['liver_disease', 'cci_score']

For your patienthistory.csv, the next cleaning step after identifying these blanks should be to inspect each of the 
10 missing cells individually and decide whether it should remain missing, be replaced with 0, 
or be reconstructed. That is preferable to simply using fillna(0) on the entire dataset.